### ISSUE TITLE
difference of convex programming?

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#1]
I don't understand the expression "difference of convex programming".   What does it mean?

**Comment by keithbriggs** [comment]
Ahh - maybe it should be "difference of convex programs"?

**Comment by jaehyunp** [comment]
The definition of difference of convex programming can be found in [this paper](https://stanford.edu/~boyd/papers/pdf/dccp.pdf).

**Comment by keithbriggs** [comment]
Now I see it - the name should be "difference-of-convex programming", then it makes sense!
K

________________________________________
