### ISSUE TITLE
Status of the problem + warm_start

### ISSUE THREAD

**Issue by mbilalzafar** [cvxgrp/dccp#12]
Hello

Is there a way to find out if the problem converged successfully or not. CVXPY has a `problem.status` filed for this purpose. However, DCCP problems don't seem to have this field (looking for `problem.status` returns nothing).

Also, the warm_start option provided in CVXPY does not seem to be there in DCCP. Could you please point out if there is a way to use warm_start in DCCP. Essentially, I am trying to solve a constrained problem, by first solving it without constraints, and then using the warm_start option to solve it with constraints (so as to provide a starting point to the constrained problem).

Thank you!

**Comment by stephenpboyd** [comment]
Those are both excellent suggestions.  We'll see what we can do.

**Comment by SteveDiamond** [comment]
If your goal is to choose the initial point for DCCP, you can do that by setting the ``var.value`` field for all the variables before solving the problem. I've updated the README to explain this. To use warm start for the convex subproblems just set ``warm_start=True``.

The question of what the ``problem.status`` field should return is a bit tricky. In general we can't say if the solution is a global minimum. And in some sense the algorithm always converges. But anything would be better than no information. We'll think about this.

**Comment by mbilalzafar** [comment]
Thank you for the answer. I tried using solver options like `warm_start` and `verbose` while calling the `problem.solve` method. While these options work for CVXPY, using them with DCCP gives an error saying `TypeError: dccp() got an unexpected keyword argument 'verbose'`. Maybe the options are not being correctly passed to the solver?

**Comment by SteveDiamond** [comment]
Sorry about that. It should work now.

**Comment by mbilalzafar** [comment]
Thanks!
