### ISSUE TITLE
pip install dccp not installing solver

### ISSUE THREAD

**Issue by citynorman** [cvxgrp/dccp#14]
I'm having trouble getting dccp solver to run, it's not showing up in cvxpy.installed_solvers(). Anything I'm doing wrong?

(venv)stn821@stn821-hp-linux:/mnt/data/dev/testvirt⟫ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
>>> cvxpy.installed_solvers()
['ECOS_BB', 'SCS', 'ECOS', 'LS']
>>> quit()
(venv)stn821@stn821-hp-linux:/mnt/data/dev/testvirt⟫ pip freeze
CVXcanon==0.1.1
cvxpy==0.4.5
dccp==0.1.5
dill==0.2.5
ecos==2.0.4
fastcache==1.0.2
multiprocess==0.70.4
numpy==1.11.1
scipy==0.18.0
scs==1.2.6
six==1.10.0
toolz==0.8.0
wsgiref==0.1.2

**Comment by SteveDiamond** [comment]
dccp doesn't go in the list of installed solvers. Maybe it should be in the list, but right now it's a method not a solver. So you write ``prob.solve(method='dccp')``. That way you can also specify which solver the dccp package uses to solve convex subproblems.

**Comment by citynorman** [comment]
Ok thanks for the quick reply!

Got it working now.

I didn't realize I needed to do:
import cvxpy
import dccp

Just did:
import cvxpy
so prob.solve(method='dccp') got a keyerror.

Might be good to include the imports in the mini examples for dummies like me :) I can see it's in the examples.
