### ISSUE TITLE
Slight probelm in the README.md

### ISSUE THREAD

**Issue by m-yaghini** [cvxgrp/dccp#20]
Hello. 
There is a small problem in the example given in the root documentation file "README.md":

```
from cvxpy import *
import dccp
x = Variable(2)
y = Variable(2)
myprob = Problem(Maximize(norm(x-y,2)), [0<=x, x<=1, 0<=y, y<=1])
print "problem is DCP:", myprob.is_dcp()   # false
print "problem is DCCP:", dccp.is_dccp(myprob)  # true
result = myprob.solve(method = 'dccp')
print "x =", x.value
print "y =", y.value
print "cost value =", result[0]
```

The above returns an Attribute Error in the 7th line; which makes sense because `dccp ` is a module not a class. To fix it, I replaced `dccp ` with `dccp.problem` in both lines 2 and 7.

**Comment by SteveDiamond** [comment]
How did you install DCCP? The example should run on the latest version, at least of the github master.

**Comment by vene** [comment]
This happens indeed with the current release from pip.  It looks like it was indeed fixed by 7113338ed1bb5dcc9b685cf3a23cf5f3930bf9d1, but it might be a good idea to have the code in the readme run with the pip version as well.

**Comment by m-yaghini** [comment]
Yes. Indeed I installed DCCP through pip. That's the first method in the readme as well, isn't it?

**Comment by SteveDiamond** [comment]
The changes are pushed to pip now.
