### ISSUE TITLE
log(exp(x)) not DCCP?

### ISSUE THREAD

**Issue by m-yaghini** [cvxgrp/dccp#21]
Hello. 

I have a problem with a rather straight-forward convex objective function and a set of non-convex but DCCP constraints. For the moment, I am trying to solve the unconstrained problem of the form:

![image](https://cloud.githubusercontent.com/assets/24247162/23168388/4956c04e-f848-11e6-840c-7fcdad2ab6bf.png)

and this is my formulation:
```
loss = sum_entries(log(np.ones((N, 1)) + exp(X * theta)) - mul_elemwise(y, X * theta))
prob = Problem(Minimize(loss))
print "Main Problem is DCCP? ", dccp.is_dccp(prob) #False
```
The original problem is demonstrably convex and DCP; in fact I managed to solve it with MATLAB CVX with ease. 

Upon further investigation, I found out that `log(exp(X * theta))` is the real culprit:

```
obj2 = sum_entries(log(exp(X * theta)))
obj3 = sum_entries(exp(X * theta))

prob2 = Problem(Minimize(obj2))
prob3 = Problem(Minimize(obj3))

print "obj2 Problem is DCCP? ", dccp.is_dccp(prob2)  #False
print "obj3 Problem is DCCP? ", dccp.is_dccp(prob3)  #True
```

So, my questions is: given that both log(.) and exp(.) are elementwise functions in CVXPY, how is it possible that log(exp(x)) is considered non-DCCP even when it is identically equal to x (with domain = R)? Is this a bug or am I missing something?

**Comment by stephenpboyd** [comment]
You're missing something.  Just read about DCP.  This is working exactly as it should.

**Comment by jaehyunp** [comment]
The `log_sum_exp` function will help: http://www.cvxpy.org/en/latest/tutorial/functions/index.html.
