### ISSUE TITLE
unable to select SCS solver

### ISSUE THREAD

**Issue by BrannonKing** [cvxgrp/dccp#24]
When I run this call:
```python
problem.solve(method='dccp', solver=SCS, max_iters=700, use_indirect=False, warm_start=True)
```
I get this exception, which implies that my request to use SCS was ignored:
```
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/problems/problem.py", line 207, in solve
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dccp/problem.py", line 36, in dccp
    dccp_ini(self, random=(ccp_times>1), **kwargs) # initialization; random initial value is mandatory if ccp_times>1
  File "/usr/local/lib/python3.5/dist-packages/dccp/problem.py", line 87, in dccp_ini
    ini_prob.solve(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/problems/solvers/ecos_intf.py", line 123, in solve
    **solver_opts)
  File "/usr/local/lib/python3.5/dist-packages/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
TypeError: 'use_indirect' is an invalid keyword argument for this function
```
My list of installed solvers: 'SCS', 'CVXOPT', 'ECOS', 'GLPK', 'GLPK_MI', 'ECOS_BB', 'LS'.
A quick look at the code comes with this theory: some places assume that solver exists in kwargs, but it is specified separately and would need to be added to kwargs manually.
Thanks for your time.

**Comment by SteveDiamond** [comment]
@xinyueshen could you take care of this? Thanks.

**Comment by xinyueshen** [comment]
@BrannonKing It works when I remove the use_indirect parameter and run the following line:
`problem.solve(method = 'dccp', solver = SCS, max_iters = 700, warm_start = True)`
It seems to me that the error has nothing to do with the solvers installed, but is due to that the parameter use_indirect is not valid. This can also be seen from the message:
`TypeError: 'use_indirect' is an invalid keyword argument for this function`

**Comment by BrannonKing** [comment]
@xinyueshen , sorry your assertion about use_indirect is not correct. It does work for SCS. The DCCP code makes multiple problem objects. However, the code doesn't pass solver to all instances of the `solve` call, but it does pass kwargs to all instances. The kwargs that goes in on the initial call needs to go with the solver choice. I think that the call at https://github.com/cvxgrp/dccp/blob/cb1ab8448c070d4e45a576debef0ad8797dabedb/dccp/problem.py#L91 should not take the original kwargs. Rather, since it appears to intentionally use the default solver, it should pass any hard-coded parameters that it knows will help in that situation.

**Comment by xinyueshen** [comment]
@BrannonKing Sorry that I misunderstood the problem. Now the bug is fixed. Thanks for pointing it out.

**Comment by BrannonKing** [comment]
While I can now select SCS, it doesn't actually run in any scenario. I get this error out of ini_prob.solve: "The solver SCS cannot solve the problem because it cannot solve unconstrained problems." Are there some constraints that we can compute for use in dccp_ini?
