### ISSUE TITLE
DCCP for non-convex (non-solid) region of L_infinite-norm

### ISSUE THREAD

**Issue by utotch** [cvxgrp/dccp#26]
Hi,
Thank you very much for an excellent tool.

I tried to a solve simple non-convex (non-solid) constrained optimization by DCCP.
The problem is successfully solved if I use L1 or L2 norm but it fails with SolverError if I use L-inf norm.
(I tried ECOS, CVXOPT, but both solvers failed.)
I expected that it could be solved but do you have any ideas of why it fails?

```
import cvxpy as cvx
import dccp
import numpy as np
x = cvx.Variable(2)
obj = cvx.Minimize(x[0] + x[1])

# constr = [cvx.norm(x, 2) <= 2, cvx.norm(x, 2) >= 1] # SUCCESS
# constr = [cvx.norm(x, 1) <= 2, cvx.norm(x, 1) >= 1] # SUCCESS
constr = [cvx.norm(x, 'inf') <= 2, cvx.norm(x, 'inf') >= 1]  # FAIL

prob = cvx.Problem(obj, constr)
print("problem is DCP:", prob.is_dcp())
print("problem is DCCP:", dccp.is_dccp(prob))
result = prob.solve(method = 'dccp')
print("x", x.value)
print("cost value =", prob.value)
```

**Comment by xinyueshen** [comment]
Thank you for reporting this problem. There was a bug in the L-inf norm subgradient calculation, and now it is fixed, so if you pull the feature/dccp branch of cvxpy and re-install it, then DCCP should be able to work for your example.
