### ISSUE TITLE
examples/test.py doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#3]
kbriggs:~/Downloads/dccp-master/examples> python test.py 
problem is DCP: False
problem is DCCP: True
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    result = myprob.solve(method = 'dccp',solver = 'MOSEK')
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/problems/problem.py", line 171, in solve
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dccp-0.1.0-py2.7.egg/dccp/problem.py", line 31, in dccp
    dccp_ini(self, random=(ccp_times>1)) # initialization; random initial value is mandatory if ccp_times>1
  File "/usr/local/lib/python2.7/dist-packages/dccp-0.1.0-py2.7.egg/dccp/problem.py", line 50, in dccp_ini
    dom_constr = self.objective.args[0].domain # domain of the objective function
AttributeError: 'pnorm' object has no attribute 'domain'

**Comment by SteveDiamond** [comment]
Are you sure you have the latest cvxpy? There was an update a few days ago to make it compatible with dccp.

**Comment by PlamenTurkedjiev** [comment]
I'm struggling to get this working, too.Tthe following, different, error crops up:

in dccp
    dccp_ini(self, random=(ccp_times>1), **kwargs) # initialization; random initial value is mandatory if ccp_times>1
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Problem(Maximize(Expression(CONVEX, NONNEGATIVE, ())), [NonPos(Expression(AFFINE, UNKNOWN, (2,))), NonPos(Expression(AFFINE, UNKNOWN, (2,))), NonPos(Expression(AFFINE, UNKNOWN, (2,))), NonPos(Expression(AFFINE, UNKNOWN, (2,)))])
times = 3, random = False, kwargs = {}, dom_constr = []
arg = NonPos(Expression(AFFINE, UNKNOWN, (2,))), l = 1

    def dccp_ini(self, times = 3, random = 0, **kwargs):
        """
        set initial values
        :param times: number of random projections for each variable
        :param random: mandatory random initial values
        """
        dom_constr = self.objective.args[0].domain # domain of the objective function
        for arg in self.constraints:
            for l in range(2):
>               for dom in arg.args[l].domain:
E               IndexError: list index out of range

**Comment by SteveDiamond** [comment]
What version of cvxpy?
