### ISSUE TITLE
Nothing happend after prob.solve

### ISSUE THREAD

**Issue by Fackie** [cvxgrp/dccp#34]
I think I set a right dccp problem, 
Actually, it's a no-restriction problem with final loss=convex1 + convex2 - convex3
![image](https://user-images.githubusercontent.com/24207392/51673526-28093f80-2009-11e9-9177-1923a170bbc1.png)

**Comment by xinyueshen** [comment]
@Fackie What is your objective function? You can look at the values of the variables and the objective function after the solve function is called to see if it works.
