### ISSUE TITLE
A practical application problem for dccp

### ISSUE THREAD

**Issue by RobertGCNiu** [cvxgrp/dccp#37]
Hello @xinyueshen , I want to use DCCP to reproduce the numerical results [in this paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6108303). 
![图片](https://user-images.githubusercontent.com/16495354/54252715-c3894c00-4586-11e9-9315-cc6117686cd9.png)
The objective f(p) - g(p) is D.C function. The result of my code can recognize it as dccp problem. However, the result of variables is **none**
```
import cvxpy as cvx
import numpy as np
from dccp.problem import is_dccp
import matplotlib.pyplot as plt
import dccp
import math

##follow the numerical design in Fast global optimal power allocation in wiereless networks by local D.C. Programming
H = np.matrix([[0.431,0.0002,0.2605,0.0039],[0.0002,0.3018,0.0008,0.0054],[0.0129,0.0005,0.4266,0.1007],[0.0011,0.0031,0.0099,0.0634]])


M = 4
ri = 1.0
w = [1.0/6,1.0/6,1.0/3,1.0/3]

p_max = [1.0,1.0,1.0,1.0]
#p_max = [0.7,0.8,0.9,1.0]
sigmal2 = 0.0001

p = cvx.Variable(M)
t = cvx.Variable(1)
constr = []
 ##The constraints: (3c) and (5)
for i in range(M-1):
    laterValue = 0
    for j in range(M-1):
        if j != i:
            laterValue = laterValue + H[j,i]*p[j]
    constr.append(H[i,i]*p[i]+(1-pow(2,ri))*(laterValue+sigmal2)>=0) ## (3c)
    constr.append(p[i]<=p_max[i]) ## (5)
    constr.append(0<=p[i])

## The objective function is reformulated as f(x)-t: t = g(x);
f_p = 0
g_p = 0
for i in range(M-1):
    laterValue_all = 0
    laterValue = 0
    for j in range(M-1):
        laterValue_all = laterValue_all + H[j,i]*p[j]
        if j != i:
            laterValue = laterValue + H[j,i]*p[j]
    f_p = f_p + w[i]*cvx.log(sigmal2 + laterValue_all)/cvx.log(2).value
    g_p = g_p + w[i]*cvx.log(sigmal2 + laterValue)/cvx.log(2).value

constr.append(t==g_p)

prob = cvx.Problem(cvx.Maximize(f_p-t),constr)
print is_dccp(prob)
prob.solve(method='dccp',ep = 1e-2)
print p.value
```

The result is 
![图片](https://user-images.githubusercontent.com/16495354/54252972-039cfe80-4588-11e9-93bb-1f292effd00d.png)

Can you please help me? I will really appreciate it.

**Comment by xinyueshen** [comment]
Hi @RobertGCNiu, I just fixed a bug, and now it can work. In this case the parameter tau needs to be set as 1.0 by `prob.solve(method='dccp', tau=1.0)`. I tried the example in the paper you mentioned, where `r_i = 0.0` and `p_max = [0.7,0.8,0.9,1.0]`, and it can find the optimum solution noted in the paper.

**Comment by RobertGCNiu** [comment]
It's cool! Thank you very much! I have already tried other parameters except for the **tau=1.0**. I should read the manual carefully.
