### ISSUE TITLE
AttributeError: 'Maximize' object has no attribute 'expr'

### ISSUE THREAD

**Issue by nyousefi13** [cvxgrp/dccp#39]
Hi,
I want to use dccp to solve a problem but none of the examples work for me. I get the following error: AttributeError: 'Maximize' object has no attribute 'expr' for the line containing 'print("problem is DCCP:", dccp.is_dccp(prob)) '
for anything I try. 
Can you please help? Thanks

**Comment by xinyueshen** [comment]
Hi @nyousefi13, the problem you encountered seems to be due to the versions. To run the updated code, please directly clone this repository and then run the examples therein (with cvxpy 1.0.21).
