### ISSUE TITLE
dead link at https://github.com/cvxgrp/dccp

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#4]
> You should first install the modified version of CVXPY hosted here.

*click*

404

**Comment by keithbriggs** [comment]
If I install the modified cxvpy, what happens to my standard installation?
Is it overwritten?
K

________________________________________

**Comment by jaehyunp** [comment]
Yes, it'll be overwritten.

**Comment by echu** [comment]
Just chiming in: virtualenv is designed to help you keep different versions
of Python libraries on your system.

If you're using anaconda, I recall a "conda env" command that does
something similar.

Hope that helps!
