### ISSUE TITLE
Possible bug or limitation

### ISSUE THREAD

**Issue by pjssilva** [cvxgrp/dccp#41]
[problem_dccp.txt](https://github.com/cvxgrp/dccp/files/3764467/problem_dccp.txt)

Hi, I tried to solve the model below and DCCP fails. If I understand the output correctly it seems like it solves a primal version and finds a optimal value close to zero (and this is not possible, the optimal value is 1), after that it tries to solve the KKT conditions to retrieve the multipliers and conclude that the related problem is and Unbounded and hence it fails and return None.

I don't see why the solver fails. Actually the problem is relatively simple. Since p == 0, the constraint on d involving p says that d == 0 too. Hence, the weird weird objective term
0.5*cvx.quad_form(b, M) + minus_norm2, which is actually a way to write -<c, d>, is 0 (as d == 0). The objective reverts to  0.5 || v ||^2 + sum(c), and the problem is actually convex even though it is written with a DC constraint. 

The problem is more interesting if p == 1, in this case it is not convex on the feasible set, and hence the problem makes more sense as a DC problem. DCCP does not solve the problem in this case either. I hope that if I can solve the problem with the DCCP when p == 0, it will also be able to solve the problem with p == 1. 

Obs: The txt is actually the Python code for the example. I had to add it as .txt because the system does not accept .py.

**Comment by pjssilva** [comment]
[problem_dccp.txt](https://github.com/cvxgrp/dccp/files/3764477/problem_dccp.txt)

**Comment by xinyueshen** [comment]
Hi @pjssilva , the parameter tau in DCCP needs to be manually set in this case. By the following code, it should work.
``result = m.solve(method="dccp", tau=1.0)``
