### ISSUE TITLE
Getting -  TypeError: cannot unpack non-iterable NotImplementedType object

### ISSUE THREAD

**Issue by MDFahimAnjum** [cvxgrp/dccp#42]
Hi,
I am getting error during DCCP solving for quadratic equality constraint with quadratic objective function.
here is my error log: 

`problem is DCP: False
problem is DCCP: True
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py in _lazyprop(self)
     26         try:
---> 27             return getattr(self, attr_name)
     28         except AttributeError:

AttributeError: 'AddExpression' object has no attribute '_lazy_canonical_form'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py in _lazyprop(self)
     26         try:
---> 27             return getattr(self, attr_name)
     28         except AttributeError:

AttributeError: 'real' object has no attribute '_lazy_canonical_form'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-24-201b47d33d25> in <module>
      9 print("problem is DCP:", myprob.is_dcp())   # false
     10 print("problem is DCCP:", dccp.is_dccp(myprob))  # true
---> 11 result = myprob.solve(method = 'dccp')
     12 print("x =", x.value)
     13 print("cost value =", result[0])

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    287         else:
    288             solve_func = Problem._solve
--> 289         return solve_func(self, *args, **kwargs)
    290 
    291     @classmethod

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/dccp-1.0.0-py3.7.egg/dccp/problem.py in dccp(self, max_iter, tau, mu, tau_max, solver, ccp_times, max_slack, ep, **kwargs)
     40         dccp_ini(self, random=(ccp_times>1), solver = solver, **kwargs) # initialization; random initial value is mandatory if ccp_times>1
     41         # iterations
---> 42         result_temp = iter_dccp(self, max_iter, tau, mu, tau_max, solver, ep, max_slack, **kwargs)
     43         if result_temp[0] is not None:
     44             if (self.objective.NAME == 'minimize' and result_temp[0]<cost_value) \

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/dccp-1.0.0-py3.7.egg/dccp/problem.py in iter_dccp(self, max_iter, tau, mu, tau_max, solver, ep, max_slack_tol, **kwargs)
    223         # solve
    224         if solver is None:
--> 225             logger.info("iteration=%d, cost value=%.5f, tau=%.5f", it, prob_new.solve(**kwargs), tau)
    226         else:
    227             logger.info("iteration=%d, cost value=%.5f, tau=%.5f", it, prob_new.solve(solver=solver, **kwargs), tau)

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    287         else:
    288             solve_func = Problem._solve
--> 289         return solve_func(self, *args, **kwargs)
    290 
    291     @classmethod

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/problems/problem.py in _solve(self, solver, warm_start, verbose, parallel, gp, qcp, **kwargs)
    567         self._construct_chains(solver=solver, gp=gp)
    568         data, solving_inverse_data = self._solving_chain.apply(
--> 569             self._intermediate_problem)
    570         solution = self._solving_chain.solve_via_data(
    571             self, data, warm_start, verbose, kwargs)

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/reductions/chain.py in apply(self, problem)
     63         inverse_data = []
     64         for r in self.reductions:
---> 65             problem, inv = r.apply(problem)
     66             inverse_data.append(inv)
     67         return problem, inverse_data

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/reductions/matrix_stuffing.py in apply(self, problem)
     98         # Batch expressions together, then split apart.
     99         expr_list = [arg for c in cons for arg in c.args]
--> 100         Afull, bfull = extractor.affine(expr_list)
    101         if 0 not in Afull.shape and 0 not in bfull.shape:
    102             Afull = cvxtypes.constant()(Afull)

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/coeff_extractor.py in affine(self, expr)
     75             expr_list = [expr]
     76         size = sum([e.size for e in expr_list])
---> 77         op_list = [e.canonical_form[0] for e in expr_list]
     78         V, I, J, b = canonInterface.get_problem_matrix(op_list, self.id_map)
     79         A = sp.csr_matrix((V, (I, J)), shape=(size, self.N))

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/coeff_extractor.py in <listcomp>(.0)
     75             expr_list = [expr]
     76         size = sum([e.size for e in expr_list])
---> 77         op_list = [e.canonical_form[0] for e in expr_list]
     78         V, I, J, b = canonInterface.get_problem_matrix(op_list, self.id_map)
     79         A = sp.csr_matrix((V, (I, J)), shape=(size, self.N))

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py in _lazyprop(self)
     27             return getattr(self, attr_name)
     28         except AttributeError:
---> 29             setattr(self, attr_name, func(self))
     30         return getattr(self, attr_name)
     31     return _lazyprop

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/canonical.py in canonical_form(self)
     38             A tuple of (affine expression, [constraints]).
     39         """
---> 40         return self.canonicalize()
     41 
     42     def variables(self):

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/atoms/atom.py in canonicalize(self)
    296             constraints = []
    297             for arg in self.args:
--> 298                 obj, constr = arg.canonical_form
    299                 arg_objs.append(obj)
    300                 constraints += constr

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py in _lazyprop(self)
     27             return getattr(self, attr_name)
     28         except AttributeError:
---> 29             setattr(self, attr_name, func(self))
     30         return getattr(self, attr_name)
     31     return _lazyprop

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/utilities/canonical.py in canonical_form(self)
     38             A tuple of (affine expression, [constraints]).
     39         """
---> 40         return self.canonicalize()
     41 
     42     def variables(self):

~/anaconda3/envs/fordccp/lib/python3.7/site-packages/cvxpy/atoms/atom.py in canonicalize(self)
    303             graph_obj, graph_constr = self.graph_implementation(arg_objs,
    304                                                                 self.shape,
--> 305                                                                 data)
    306             return graph_obj, constraints + graph_constr
    307 

TypeError: cannot unpack non-iterable NotImplementedType object
`

**Comment by xinyueshen** [comment]
Hi @MDFahimAnjum, the problem seems to be that you're using Python3.7, but DCCP is currently written in Python2. I mean to update the code to work with Python3, but it might take a while. Now you could try to install dccp from source and then run it with CVXPY 1.0.21 and Python2. If that still doesn't work, you could post your optimization problem here, and I'm willing to look into it.

**Comment by gcasamat** [comment]
Hi all. I am running into the same error message (I tried with both python 3 and 2). Here is the code:
`import cvxpy as cvx
import dccp
yll = cvx.Variable(nonneg=True)
ylh = cvx.Variable(nonneg=True)
yhl = cvx.Variable(nonneg=True)
yhh = cvx.Variable(nonneg=True)
T_yll = cvx.Variable(1)
T_ylh = cvx.Variable(1)
T_yhl = cvx.Variable(1)
T_yhh = cvx.Variable(1)
bl = cvx.Variable(nonneg=True)
bh = cvx.Variable(nonneg=True)
T_bl = cvx.Variable(1)
T_bh = cvx.Variable(1)
wl = cvx.Parameter(nonneg=True)
wh = cvx.Parameter(nonneg=True)
pl = cvx.Parameter(nonneg=True)
ph = cvx.Parameter(nonneg=True)
Nl = cvx.Parameter(nonneg=True)
Nh = cvx.Parameter(nonneg=True)
gamma = cvx.Parameter(nonneg=True)
wl.value = 1
wh.value = 10
pl.value = 1/2
ph.value = 1/2
Nl.value = 1
Nh.value = 1
gamma.value = 0.5
alpha = 4
beta = 4
u_ll = (1/(1-alpha))*cvx.power(yll-T_yll+bl-T_bl-bl,1-alpha) - (1/beta)*cvx.power(yll/wl,beta)
u_lh = (1/(1-alpha))*cvx.power(ylh-T_ylh+bh-T_bh-bl,1-alpha) - (1/beta)*cvx.power(ylh/wl,beta)
u_hl = (1/(1-alpha))*cvx.power(yhl-T_yhl+bl-T_bl-bh,1-alpha) - (1/beta)*cvx.power(yhl/wh,beta)
u_hh = (1/(1-alpha))*cvx.power(yhh-T_yhh+bh-T_bh-bh,1-alpha) - (1/beta)*cvx.power(yhh/wh,beta)
omega_l = pl*u_ll + ph*u_hl
omega_h = pl*u_lh + ph*u_hh
u_hh_lh_joint = (1/(1-alpha))*cvx.power(ylh-T_ylh+bh-T_bh-bl,1-alpha) - (1/beta)*cvx.power(ylh/wh,beta)
budg_constr_y = Nl*pl*T_yll + Nh*pl*T_ylh + Nl*ph*T_yhl + Nh*ph*T_yhh
budg_constr_b = Nl*T_bl + Nh*T_bh 
soc_wel = -(Nl*pl*u_ll + Nh*pl*u_lh + Nl*ph*u_hl + Nh*ph*u_hh)
obj = cvx.Minimize(soc_wel)
constraints = [budg_constr_y >= 0, budg_constr_b >= 0]
prob_unconstr = cvx.Problem(obj, constraints)
prob_unconstr.solve()
constraints = [budg_constr_y >= 0, budg_constr_b >= 0, u_hh + gamma*omega_h >= u_hh_lh_joint + gamma*omega_l]
prob = cvx.Problem(obj, constraints)
dccp.is_dccp(prob)
prob.solve(method='dccp')`

**Comment by xinyueshen** [comment]
@gcasamat The DCCP source code just got updated, and now I can run your example without error. Please have a try and make sure that CVXPY is correctly installed and your DCCP package is also updated.

**Comment by gcasamat** [comment]
I will have a look, thanks a lot.

 

De : Xinyue Shen <notifications@github.com>
Répondre à : cvxgrp/dccp <reply@reply.github.com>
Date : mercredi 22 janvier 2020 à 22:48
À : cvxgrp/dccp <dccp@noreply.github.com>
Cc : gcasamat <geocas@free.fr>, Mention <mention@noreply.github.com>
Objet : Re: [cvxgrp/dccp] Getting - TypeError: cannot unpack non-iterable NotImplementedType object (#42)

 

@gcasamat The DCCP source code just got updated, and now I can run your example without error. Please have a try and make sure that CVXPY is correctly installed and your DCCP package is also updated.

**Comment by gcasamat** [comment]
Hi. I made a test, but unfortunately I get the same error message as before. 

Georges

 

De : Xinyue Shen <notifications@github.com>
Répondre à : cvxgrp/dccp <reply@reply.github.com>
Date : mercredi 22 janvier 2020 à 22:48
À : cvxgrp/dccp <dccp@noreply.github.com>
Cc : gcasamat <geocas@free.fr>, Mention <mention@noreply.github.com>
Objet : Re: [cvxgrp/dccp] Getting - TypeError: cannot unpack non-iterable NotImplementedType object (#42)

 

@gcasamat The DCCP source code just got updated, and now I can run your example without error. Please have a try and make sure that CVXPY is correctly installed and your DCCP package is also updated.
