### ISSUE TITLE
Problem.status in None in DCCP

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#44]
According to https://www.cvxpy.org/api_reference/cvxpy.problems.html, status has to be a string and one of optimal, infeasible, or unbounded. But with solver='dccp', I'm often getting a None value (apparently when the solver has failed, since constraints are violated). What could cause this?

In fact even the first DCCP example has this problem:

import cvxpy as cvx
import dccp
x = cvx.Variable(2)
y = cvx.Variable(2)
myprob = cvx.Problem(cvx.Maximize(cvx.norm(x-y,2)), [0<=x, x<=1, 0<=y, y<=1])
print("problem is DCP:", myprob.is_dcp()) # false
print("problem is DCCP:", dccp.is_dccp(myprob)) # true
result = myprob.solve(method = 'dccp')
print("x =", x.value)
print("y =", y.value)
print("cost value =", result[0])
print("status =",myprob.status) # prints "None"
print("status =",myprob._status) # prints "None"

**Comment by xinyueshen** [comment]
Hi @keithbriggs , thanks for reporting this problem. The status of the DCCP solver should be either converged or not converged, and I just have it fixed, so now when you run the example, it should output:
`print("status =",myprob.status) # prints 'Converged'`

**Comment by keithbriggs** [comment]
Thanks for fixing this - the status problem has now gone away.   However, my old code which used to work is now raising this exception when I call solve:

'<' not supported between instances of 'list' and 'float'

What might cause this?

**Comment by xinyueshen** [comment]
@keithbriggs It looks like one side of your '<' inequality is identified as a list. Would you like to share your code where this happens?

**Comment by xinyueshen** [comment]
@keithbriggs I see you opened another issue on this. I'll work with you there.

**Comment by keithbriggs** [comment]
The code is in another issue "dccp fails if ccp_times>1 in call to solve<https://github.com/cvxgrp/dccp/issues/46>".


This is a bug in your solver, not my code.


Keith

________________________________
