### ISSUE TITLE
dccp fails if ccp_times>1 in call to solve

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#46]
If ccp_times is >1, then there is a crash in this line:

    if t==0 or len(result_temp)<3 or result[1] < max_slack:

because result_temp[1], which is returned by iter_dccp, is a list of arrays.

Keith

**Comment by keithbriggs** [comment]
For example:

    import cvxpy as cvx 
    import dccp
    x = cvx.Variable(2)
    y = cvx.Variable(2)
    myprob = cvx.Problem(cvx.Maximize(cvx.norm(x-y,2)), [0<=x, x<=1, 0<=y, y<=1])
    print("problem is DCP:", myprob.is_dcp())   # false
    print("problem is DCCP:", dccp.is_dccp(myprob))  # true
    result = myprob.solve(method = 'dccp', ccp_times=5)
    print("x =", x.value)
    print("y =", y.value)
    print("cost value =", result[0])
    print("result =", result)
    print("status =",myprob.status) 

> python3 try_dccp_00.py 
problem is DCP: False
problem is DCCP: True
Traceback (most recent call last):
  File "try_dccp_00.py", line 8, in <module>
    result = myprob.solve(method = 'dccp', ccp_times=5)
  File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.0a1-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 310, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.0-py3.6.egg/dccp/problem.py", line 53, in dccp
    if t==0 or len(result_temp)<3 or result[1] < max_slack:
TypeError: '<' not supported between instances of 'list' and 'float

**Comment by keithbriggs** [comment]
Can someone look at this?   It is a serious bug in DCCP.

**Comment by xinyueshen** [comment]
Thanks. Bug fixed.
