### ISSUE TITLE
How to process the constraint like huber(x)>=0

### ISSUE THREAD

**Issue by Noilyn** [cvxgrp/dccp#47]
Hi, I met the error below when trying to solve a logistic regression problem with constraint "huber(x)>=0"

TypeError: cannot unpack non-iterable NotImplementedType object.

The problem has passed the DCCP test (dccl.is_dccp(problem) == True), I've tried both python2 and python3 but nothing changed. 
Hoping for help, Thanks.

**Comment by xinyueshen** [comment]
It looks like some packages are not correctly installed. Did you use CVXPY 1.0 and the most updated DCCP code from source?

**Comment by Noilyn** [comment]
Yeah, I think I made it.  I've passed the example code from source.
