### ISSUE TITLE
import dccp fails when run from a readonly location

### ISSUE THREAD

**Issue by rhkleijn** [cvxgrp/dccp#48]
Currently importing dccp when python is run from a readonly location raises an error: 

> C:\>python -c "import dccp"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Miniconda3\envs\dev37\lib\site-packages\dccp\__init__.py", line 1, in <module>
>     from dccp.problem import is_dccp
>   File "C:\Miniconda3\envs\dev37\lib\site-packages\dccp\problem.py", line 13, in <module>
>     logger.addHandler(logging.FileHandler(filename='dccp.log', mode='w'))
>   File "C:\Miniconda3\envs\dev37\lib\logging\__init__.py", line 1087, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "C:\Miniconda3\envs\dev37\lib\logging\__init__.py", line 1116, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> PermissionError: [Errno 13] Permission denied: 'C:\\dccp.log'

(and when importing from a location with write permissions an empty `dccp.log` is created.)

This happens because `import dccp` tries to create an (empty) `dccp.log` file in this line from `problem.py`:
`logger.addHandler(logging.FileHandler(filename='dccp.log', mode='w'))`.

My preferred solution would be to drop this line entirely and let the application importing dccp decide which logging handlers to use.
An other (more opt-out kind of ) solution would be to change it into `logger.addHandler(logging.FileHandler(filename='dccp.log', mode='w', delay=True))` which prevents the immediate writing of the `dccp.log` file and gives the application importing dccp the option to drop the handler before an actual write is attempted.

**Comment by xinyueshen** [comment]
Fixed. Thanks!

**Comment by rhkleijn** [comment]
Thanks for fixing this! Are you planning to do a release with this fix included? If so, could you also consider releasing it as a conda package (like many of the other cvxgrp packages)?

**Comment by xinyueshen** [comment]
Thanks @rhkleijn. Will do that.

**Comment by SteveDiamond** [comment]
@xinyueshen are you able to put packages on pip? If not, let me know and I'll help. Having a conda package would have some value, but you can also install using pip with a conda setup.

**Comment by xinyueshen** [comment]
Hi @SteveDiamond thanks a lot!! I haven't put any package on pip or conda before, so it would be really helpful if you have time to help with it.

**Comment by xinyueshen** [comment]
@SteveDiamond Thanks!
