### ISSUE TITLE
DCCP problem

### ISSUE THREAD

**Issue by HuiHu1** [cvxgrp/dccp#50]
My dccp programming returns the following error, what's the reason? Thanks!

return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, **kwargs)
TypeError: argument 12 must be bool, not str

**Comment by xinyueshen** [comment]
Hi @HuiHu1, what's your optimization problem? You could share it here and I'll look into the error.

**Comment by crmccreary** [comment]
For several of the example problems, cvxpy throws the following exception:

TypeError: 'NotImplementedType' object is not iterable

The version of cvxpy is 1.0.31.
Python version 2.7.12

**Comment by xinyueshen** [comment]
@crmccreary Please download or clone the repo to use the most updated DCCP. Then this error should be gone.
