### ISSUE TITLE
Matmul depreciation warning 

### ISSUE THREAD

**Issue by Kreol64** [cvxgrp/dccp#53]
Hi, 

I am using dccp==1.0.0 and cvxpy==1.1.1 (I wasn`t able to make a newer dccp version work ) I cannot get rid of depreciation warning when I use dccp.

```
UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
```

1) I do not have "*" in my problem configuration so I assume dccp uses it somewhere under the hood.
2) I tried to ignore warnings before the import of dccp

```
import warnings
warnings.filterwarnings('ignore',category=UserWarning)
```

But that didn`t help. Could you please help ? I see 14 warnings in a row each time I solve the problem.

**Comment by xinyueshen** [comment]
Hi @Kreol64, DCCP works with CVXPY 1.0 but not 1.1 yet, so you could switch CVXPY back to version 1.0.21. You may want to use the most updated code of DCCP via cloning/downloading the package and installing it by running `python setup.py install `.

**Comment by xinyueshen** [comment]
@Kreol64 Did you install dccp 1.0.2 from pip? If so, it is not the most updated code, and you may want to use the most updated code by directly cloning this repo. 
If you've already used the most updated code, what is your optimization problem?

**Comment by Kreol64** [comment]
@xinyueshen we work as a study group so it`s a bit easier to do version control and deployment with package installation so that everyone has the same copy. Is there a big difference in functionality?

**Comment by xinyueshen** [comment]
@Kreol64 A few bugs are fixed in the most updated code. But even with the package 1.0.2 installed from pip, I can run the code in #42 without error. Would you like to share the form of your optimization problem and the error message here?

**Comment by SteveDiamond** [comment]
Fixed.
