### ISSUE TITLE
TypeError: cannot unpack non-iterable NotImplementedType object

### ISSUE THREAD

**Issue by supremefist** [cvxgrp/dccp#57]
Hi,

I have a piece of code, which works with Python 2.7 and the following packages:
- cvxpy-0.4.8
- dccp-0.1.5

The piece of code is as follows:
```
import cvxpy as cvx
import numpy as np

from dccp.problem import dccp

cvx.Problem.register_solve("dccp", dccp)

means = np.array([-0.3, 0.2, -0.002])
stds = np.array([0.2, 0.05, 0.02])

params = {
    "k1": 3.0,
    "k2": 1.0,
    "net_weight": 0.0,
    "max_positive_weight": 1.0,
    "max_negative_weight": 1.0,
    "min_weight_norm_sum": 2.0,
    "penalty_scale_factor": 5.0
}

cvx_params = {
    "k1": cvx.Parameter(sign='positive', value=params['k1']),
    "m_min": cvx.Parameter(sign='positive', value=params['min_weight_norm_sum']),
    "m_neg_S": cvx.Parameter(sign='positive', value=params['max_negative_weight']),
    "m_pos_S": cvx.Parameter(sign='positive', value=params['max_positive_weight']),
    "m_net": cvx.Parameter(sign='positive', value=params['net_weight'])
}

cvx_variables = {
    "w": cvx.Variable(len(means))
}

cvx_variables["w"].value = np.array([-1.5, 3., -1.5])

cvx_variables["sigma_P"] = cvx.norm(cvx.mul_elemwise(stds, cvx_variables['w']), "fro")
cvx_variables["mu_P"] = cvx.sum_entries(cvx.mul_elemwise(means, cvx_variables['w']))

cvx_objective = {'function': cvx_params['k1'] * cvx_variables['sigma_P'] - cvx_variables['mu_P']}

cvx_constraints = {
    'c1': [cvx.norm(cvx_variables['w'], 1) == cvx_params['m_min']],
    'c2': [-cvx_params['m_neg_S'] <= cvx_variables['w'], cvx_variables['w'] <= cvx_params['m_pos_S']],
    'c3': [],
    'c4': [cvx.sum_entries(cvx_variables['w']) == cvx_params['m_net']]
}

cvx_constraints['main'] = cvx_constraints['c1'] + cvx_constraints['c2'] + cvx_constraints['c3'] + cvx_constraints['c4']

cvx_prob = cvx.Problem(cvx.Minimize(cvx_objective['function']), cvx_constraints['main'])
result = cvx_prob.solve(method='dccp', solver="ECOS", max_iter=1000, verbose=False)

print("Solution status: %s" % (cvx_prob.status))

weights = np.array(cvx_variables['w'].value).flatten()

np.testing.assert_almost_equal(weights, np.array([-0.16210367, 1., -0.83789633]), decimal=5)
print("Solved correctly!")
```

And it gives the following output:
> iteration= 1 cost value =  -0.0645990885531 tau =  0.005
> max slack =  5.10001621344e-09
> iteration= 2 cost value =  -0.0645990885542 tau =  0.006
> max slack =  3.90931148962e-09
> Solution status: Converged
> Solved correctly!

On a Python 3.7 installation I have installed the latest version of dccp through pip and this gave me the following packages:
- cvxpy-1.1.1 
- dccp-1.0.2

I slightly changed the above code to be compatible with the latest DCCP and CVXPY:

```
import cvxpy as cvx
import numpy as np

from dccp.problem import dccp

cvx.Problem.register_solve("dccp", dccp)

means = np.array([-0.3, 0.2, -0.002])
stds = np.array([0.2, 0.05, 0.02])

params = {
    "k1": 3.0,
    "k2": 1.0,
    "net_weight": 0.0,
    "max_positive_weight": 1.0,
    "max_negative_weight": 1.0,
    "min_weight_norm_sum": 2.0,
    "penalty_scale_factor": 5.0
}

cvx_params = {
    "k1": cvx.Parameter(nonneg=True, value=params['k1']),
    "m_min": cvx.Parameter(nonneg=True, value=params['min_weight_norm_sum']),
    "m_neg_S": cvx.Parameter(nonneg=True, value=params['max_negative_weight']),
    "m_pos_S": cvx.Parameter(nonneg=True, value=params['max_positive_weight']),
    "m_net": cvx.Parameter(nonneg=True, value=params['net_weight'])
}

cvx_variables = {
    "w": cvx.Variable(len(means))
}

cvx_variables["w"].value = np.array([-1.5, 3., -1.5])

cvx_variables["sigma_P"] = cvx.norm(cvx.multiply(stds, cvx_variables['w']))
cvx_variables['mu_P'] = cvx.sum(cvx.multiply(means, cvx_variables['w']))

cvx_objective = {'function': cvx_params['k1'] * cvx_variables['sigma_P'] - cvx_variables['mu_P']}

cvx_constraints = {
    'c1': [cvx.norm(cvx_variables['w'], 1) == cvx_params['m_min']],
    'c2': [-cvx_params['m_neg_S'] <= cvx_variables['w'], cvx_variables['w'] <= cvx_params['m_pos_S']],
    'c3': [],
    'c4': [cvx.sum(cvx_variables['w']) == cvx_params['m_net']]
}

cvx_constraints['main'] = cvx_constraints['c1'] + cvx_constraints['c2'] + cvx_constraints['c3'] + cvx_constraints['c4']

cvx_prob = cvx.Problem(cvx.Minimize(cvx_objective['function']), cvx_constraints['main'])
result = cvx_prob.solve(method='dccp', solver="ECOS", max_iter=1000, verbose=False)

print("Solution status: %s" % (cvx_prob.status))
weights = np.array(cvx_variables['w'].value).flatten()

np.testing.assert_almost_equal(weights, np.array([-0.16210367, 1., -0.83789633]), decimal=5)
print("Solved correctly!")
```

but this gives me the following ouput:
> /home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
> This use of ``*`` has resulted in matrix multiplication.
> Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
>     Use ``*`` for matrix-scalar and vector-scalar multiplication.
>     Use ``@`` for matrix-matrix and matrix-vector multiplication.
>     Use ``multiply`` for elementwise multiplication.
> 
>   warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
> Traceback (most recent call last):
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 33, in _lazyprop
>     return getattr(self, attr_name)
> AttributeError: 'AddExpression' object has no attribute '_lazy_canonical_form'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 33, in _lazyprop
>     return getattr(self, attr_name)
> AttributeError: 'NegExpression' object has no attribute '_lazy_canonical_form'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 33, in _lazyprop
>     return getattr(self, attr_name)
> AttributeError: 'AddExpression' object has no attribute '_lazy_canonical_form'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 33, in _lazyprop
>     return getattr(self, attr_name)
> AttributeError: 'real' object has no attribute '_lazy_canonical_form'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "optimise_py3.py", line 50, in <module>
>     result = cvx_prob.solve(method='dccp', solver="ECOS", max_iter=1000, verbose=False)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 395, in solve
>     return solve_func(self, *args, **kwargs)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/dccp/problem.py", line 42, in dccp
>     result_temp = iter_dccp(self, max_iter, tau, mu, tau_max, solver, ep, max_slack, **kwargs)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/dccp/problem.py", line 243, in iter_dccp
>     logger.info("iteration=%d, cost value=%.5f, tau=%.5f", it, prob_new.solve(solver=solver, **kwargs), tau)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 395, in solve
>     return solve_func(self, *args, **kwargs)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 744, in _solve
>     solver, gp, enforce_dpp)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 524, in get_problem_data
>     data, inverse_data = solving_chain.apply(self)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/reductions/chain.py", line 71, in apply
>     problem, inv = r.apply(problem)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 314, in apply
>     params_to_problem_data = extractor.affine(expr_list)
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/coeff_extractor.py", line 82, in affine
>     op_list = [e.canonical_form[0] for e in expr_list]
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/coeff_extractor.py", line 82, in <listcomp>
>     op_list = [e.canonical_form[0] for e in expr_list]
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 35, in _lazyprop
>     setattr(self, attr_name, func(self))
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/canonical.py", line 42, in canonical_form
>     return self.canonicalize()
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 315, in canonicalize
>     obj, constr = arg.canonical_form
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 35, in _lazyprop
>     setattr(self, attr_name, func(self))
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/canonical.py", line 42, in canonical_form
>     return self.canonicalize()
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 315, in canonicalize
>     obj, constr = arg.canonical_form
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 35, in _lazyprop
>     setattr(self, attr_name, func(self))
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/canonical.py", line 42, in canonical_form
>     return self.canonicalize()
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 315, in canonicalize
>     obj, constr = arg.canonical_form
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 35, in _lazyprop
>     setattr(self, attr_name, func(self))
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/utilities/canonical.py", line 42, in canonical_form
>     return self.canonicalize()
>   File "/home/riaan/.virtualenvs/empiric/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 322, in canonicalize
>     data)
> TypeError: cannot unpack non-iterable NotImplementedType object

There appears to be an incompatibility between the latest version of DCCP and CVXPY. Any assistance would be appreciated!

Kind regards,
Riaan

**Comment by xinyueshen** [comment]
Hi @supremefist, DCCP currently works with CVXPY 1.0, not CVXPY 1.1, so you could try CVXPY1.0.31 to see if it works.

**Comment by pbpf** [comment]
Simply replace 
```
 real(left - right) <= 0
```
 with
```
left - right<= 0
```
in constraint.py may solve this.

**Comment by SteveDiamond** [comment]
Works for me with latest dccp (installed via pip).
