### ISSUE TITLE
DOC: ambiguity

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#58]
When the docs says:

     In a disciplined convex-concave program, by contrast, the objective and right and left-hand sides of the constraints can have any curvature, so long as all expressions satisfy the DCP composition rules.

does that mean that the constraints can have any curvature, _so long as it is known_?

**Comment by xinyueshen** [comment]
@keithbriggs Yes, it means that the left-hand side and the right-hand side of a constraint can have any known curvature.

**Comment by keithbriggs** [comment]
Thanks - same for the objective, I suppose.

Keith

________________________________

**Comment by xinyueshen** [comment]
Yes, the objective can have any known curvature.

**Comment by keithbriggs** [comment]
Good, thanks.  Another problem: my objective is something like cp.quad_form(x,A), where A is Hermitian +ve definite, so this is real and known to be convex.   But I get the error message from dccp:

    ValueError: The 'maximize' objective must be real valued.

What's it testing to get this?    Are there tiny imaginary parts due to round-off errors?    if so, how can I strip them and keep it DCP?

**Comment by xinyueshen** [comment]
Bug fixed. The following example works.
```
A = np.array([[100, 1-2j, 3+5j], [1+2j, 100, -9+1j], [3-5j, -9-1j, 100]])
x = cp.Variable(3)
expr = cp.quad_form(x, A)
prob = cp.Problem(cp.Maximize(expr), [expr <= 1])
dccp.is_dccp(prob)
prob.solve(method='dccp')
```

**Comment by keithbriggs** [comment]
Thank you!

**Comment by keithbriggs** [comment]
It's actually reporting Not_converged on this example.

**Comment by xinyueshen** [comment]
I got Converged when I tried. Did you set an initial value for x manually?

**Comment by keithbriggs** [comment]
No, I just used the exact code you posted.  Also I tried larger HPD matrices, using this function:

```
def random_HPD(n):
  P=np.random.randn(n,n)+1j*np.random.randn(n,n)
  return np.conjugate(P.T)@P
```

**Comment by xinyueshen** [comment]
Code
```
import cvxpy as cp
import numpy as np
import dccp 

def random_HPD(n):
    P=np.random.randn(n,n)+1j*np.random.randn(n,n)
    return np.conjugate(P.T)@P

n = 100
A = random_HPD(n)
x = cp.Variable(n)
expr = cp.quad_form(x, A)
prob = cp.Problem(cp.Maximize(expr), [expr <= 1])
dccp.is_dccp(prob)
prob.solve(method='dccp')
print("status", prob.status)
print("obj value", expr.value)
```
Result
```
status Converged
obj value (0.9999998125233991+1.0408340855860843e-17j)
```

**Comment by keithbriggs** [comment]
That gives me 

`cvxpy.error.SolverError: Solver 'ECOS' failed.`

But solver='SCS' does converge.

In general, we need a random seed to get reproducible test examples. 

A problem more like the real ones I want to do has

`prob = cp.Problem(cp.Maximize(expr), [cp.norm(x) <= 1])`

For this, I am getting Not_converged, but the solution might actually be ok.

**Comment by xinyueshen** [comment]
We could give it more iterations to converge.
```
import cvxpy as cp
import numpy as np
import dccp 

def random_HPD(n):
    P=np.random.randn(n,n)+1j*np.random.randn(n,n)
    return np.conjugate(P.T)@P

np.random.seed(0)
n = 100
A = random_HPD(n)
x = cp.Variable(n)
expr = cp.quad_form(x, A)
prob = cp.Problem(cp.Maximize(expr), [cp.norm(x) <= 1])
dccp.is_dccp(prob)
prob.solve(method='dccp', solver='SCS', max_iter=200)
print("status", prob.status)
print("obj value", expr.value)
```

**Comment by keithbriggs** [comment]
Yes, that works, although the final objective value comes out with a small imaginary component, which should be impossible as the objective is real-valued.

I think quad_form should enforce a real return value, since it assumes Hermitian anyway.   This could be a cvxpy issue.

Keith

________________________________

**Comment by xinyueshen** [comment]
This is also fixed in cvxpy.
