### ISSUE TITLE
ValueError: Inequality constraints cannot be complex

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#62]
This code works:
```
def random_HPD(n):
  P=np.random.randn(n,n)+1j*np.random.randn(n,n)
  return np.conjugate(P.T)@P

def test_00a(n=8): # Hermitian example
  A=random_HPD(n)
  x=cp.Variable(n,complex=True)
  expr=cp.quad_form(x,A)
  prob=cp.Problem(cp.Maximize(expr),[cp.norm(x)<=1])
  dccp.is_dccp(prob)
  r=prob.solve(method='dccp')
  print(r)
```

However, changing cp.norm(x)<=1 to cp.norm(x)==1 results in the error below.  The message "Inequality constraints cannot be complex" does not make sense because this was an equality constraint, and norm is not complex.  Anyway, the solution should be the same in both cases.

> cvxpy.__version__= 1.1.0a1
> dccp.__version__ = 1.0.3
> Traceback (most recent call last):
>   File "try_dccp_00.py", line 98, in <module>
>     test_00a()
>   File "try_dccp_00.py", line 37, in test_00a
>     r=prob.solve(method='dccp')
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.0a1-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 310, in solve
>     return solve_func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/problem.py", line 55, in dccp
>     self, max_iter, tau, mu, tau_max, solver, ep, max_slack, **kwargs
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/problem.py", line 241, in iter_dccp
>     temp = convexify_constr(arg)
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/constraint.py", line 84, in convexify_constr
>     return left - right <= 0, dom
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.0a1-py3.6-linux-x86_64.egg/cvxpy/expressions/expression.py", line 46, in cast_op
>     return binary_op(self, other)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.0a1-py3.6-linux-x86_64.egg/cvxpy/expressions/expression.py", line 573, in __le__
>     return Inequality(self, other)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.0a1-py3.6-linux-x86_64.egg/cvxpy/constraints/nonpos.py", line 86, in __init__
>     raise ValueError("Inequality constraints cannot be complex.")
> ValueError: Inequality constraints cannot be complex.

**Comment by xinyueshen** [comment]
The bug is fixed. Now DCCP should be able to handle real-valued functions with complex variables correctly.

**Comment by keithbriggs** [comment]
Thanks very much - it's working pretty well now!
