### ISSUE TITLE
Not converged in a DC problem

### ISSUE THREAD

**Issue by MarkYuanyuan** [cvxgrp/dccp#63]
Hi,  I'm trying to solve a DC problem 'x^4 - (x^2 + x)' for example, whose optimal value could be found as -1.055 at x=0.8846 with classic DC algorithm,  but I found I couldn't solve it with dccp:
import cvxpy as cvx
import dccp
x = cvx.Variable(1)
t = cvx.Variable(1)
myprob = cvx.Problem(cvx.Minimize(x**4 - t), [t == x**2 + x])
print("problem is DCP:", myprob.is_dcp())   # f=False
print("problem is DCCP:", dccp.is_dccp(myprob))  # True
result = myprob.solve(method = 'dccp')
print("x =", x.value)
print("status =", myprob.status) # prints 'Not_Converged'
print("cost value =", result[0])

which is 'Not_Converged'. Thanks a lot for your help!

**Comment by xinyueshen** [comment]
Hi @MarkYuanyuan, in this example a parameter needs to be set as follows.
```
result = myprob.solve(method='dccp', tau=1.0)
```
