### ISSUE TITLE
subproblem is not DCP

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#64]
I'm quite often getting errors like this.  I added a print at line 42 of dcp2cone.py, and it's confirming that it was passed a non-DCP minimization problem.   How can this happen?   Another thing - my problems are have complex variables, and I don't understand how the convexification in DCCP works in this case.   Why aren't the gradient terms added to objective and constraints complex-valued, which would conflict with the requirement to be real?

>   File "try_simultaneous_diagonalization_01.py", line 118, in solve_constrained_RR
>     result=prob.solve(method='dccp',solver=solver,ccp_times=ccp_times,mu=mu,tau=tau,eps=eps,max_iters=max_iters,verbose=False,warm_start=True)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 396, in solve
>     return solve_func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/problem.py", line 55, in dccp
>     self, max_iter, tau, mu, tau_max, solver, ep, max_slack, **kwargs
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/problem.py", line 281, in iter_dccp
>     prob_new_cost_value = prob_new.solve(solver=solver, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 396, in solve
>     return solve_func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 745, in _solve
>     solver, gp, enforce_dpp)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 525, in get_problem_data
>     data, inverse_data = solving_chain.apply(self)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/reductions/chain.py", line 71, in apply
>     problem, inv = r.apply(problem)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/reductions/dcp2cone/dcp2cone.py", line 43, in apply
>     raise ValueError("Cannot reduce problem to cone program")
> ValueError: Cannot reduce problem to cone program

**Comment by SteveDiamond** [comment]
Fundamentally DCCP was not designed to handle complex variables.

**Comment by xinyueshen** [comment]
Right, DCCP simply turns a complex variables x+jy into a concatenated real variable (x, y), so there is no complex value in the convexified problem. You could do such conversion yourself if needed.

For errors reporting the passed problem is not DCP, you could check the curvature of your functions.

**Comment by keithbriggs** [comment]
Ok, thanks.   I am creating an objective and constraints only using cp.norm() and cp.quad_form with a Hermitian +ve definite matrix, so my curvatures are all ok.   The non-DCP subproblem is being created by DCCP (as you can see from my stack trace).   I can't see how this is possible.

________________________________

**Comment by keithbriggs** [comment]
Ok, I will try the manual conversion.   On the other hand, for the naturally real-valued case of Hermitian forms, there might be an elegant way to keep the complex variables.

**Comment by xinyueshen** [comment]
The norm and quad_form should work... What is the optimization problem that gives that non-DCP error?

**Comment by keithbriggs** [comment]
The general structure is:

```
  obj=cp.quad_form(x,A)
  con=[cp.norm(x)==1,cp.quad_form(x,A0)==cp.quad_form(x,A1),]
```

All matrices are HPD.   Small matrices are ok, but it breaks down as matrices get bigger, and maybe my matrices have some eigenvalues close to zero.  I could try to make a MWE tomorrow.

 I also don't understand why replacing the second constraint by cp.quad_form(B0@x,A0)==cp.quad_form(B1@x,A1) doesn't work.  It should be equivalent with a different matrix.

**Comment by keithbriggs** [comment]
I'm trying some things.   One issue is this.  It should be ok as z.H@z is convex (and the cp.real should not be needed).

```
  z=cp.Variable(n,complex=True)
  obj=cp.real(z.H@z)
  prob=cp.Problem(cp.Minimize(obj))
```

> cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
> The objective is not DCP. Its following subexpressions are not:
> conj(var0) @ var0
>

**Comment by xinyueshen** [comment]
`z.H@z` is convex but not DCP. DCP does not accept multiplication between two variables. Instead, you can use norm, quad_form, etc.

**Comment by xinyueshen** [comment]
I've tested the following with different random seeds, and it works fine.
```
def random_HPD(n):
    P=np.random.randn(n,n)+1j*np.random.randn(n,n)
    return np.conjugate(P.T)@P
n = 100
A = random_HPD(n)
A0 = random_HPD(n)
A1 = random_HPD(n)
x = cp.Variable(n, complex=True)
obj=cp.quad_form(x, A)
con=[cp.norm(x)==1, cp.quad_form(x,A0)==cp.quad_form(x,A1)]
```

**Comment by keithbriggs** [comment]
Right, but I was suggesting x*x could be allowed.

Keith

________________________________

**Comment by keithbriggs** [comment]
Yes, I have been doing similar tests.   This is exactly my problem structure, but there must be something special about my matrices which are failing (maybe close to singular).  I sometimes get "cannot reduce to cone program".   I am investigating....


________________________________

**Comment by keithbriggs** [comment]
Here is an example of handling complex variables in penalty CCP, without explicitly splitting into real and imag parts.    The performance isn't great (I think it gets stuck in local minima), but it's an instructive example and I'm still working on it.

```
def random_HPD(n):
  P=np.random.randn(n,n)+1j*np.random.randn(n,n)
  return np.conjugate(P.T)@P

def test_02(n=4):
  ' max_z z^H@A@z s.t. z^H@z=1 '
  A=random_HPD(n)
  w,v=eigh(A,np.eye(n),check_finite=False)
  r=np.random.randn(n)+1j*np.random.randn(n)
  zk=v[-1]+1e-1*r
  tau,mu=5e-3,1.2
  z=cp.Variable(n,complex=True)
  s=cp.Variable(2,pos=True)
  for i in range(50):
    # z^H@z linearized...
    g0=cp.real(np.conj(zk)@z+z.H@zk-cp.norm(z))
    # constrain z^H@z==1
    con=[-1+np.linalg.norm(zk)-g0<=s[0],
         -1+cp.norm(z)           <=s[1]]
    # z^H@A@z linearized...
    g1=cp.real(np.conj(zk)@A@z+z.H@A@zk-cp.quad_form(z,A))
    prob=cp.Problem(cp.Minimize(-g1+tau*cp.sum(s)),con)
    sol=prob.solve(solver='SCS',warm_start=True)
    print('tau=%.3f'%tau,'obj=%.6f'%(-sol,),'z=',z.value,'|s|=%g'%(np.linalg.norm(s.value),),'|z|-1=%g'%(np.linalg.norm(z.value)-1,))
    zk=z.value
    tau*=1.2
  print('exact answer            =',v[-1])
```

> tau=0.005 obj=6.484632 z= [-0.5890-0.2311j -0.3283-0.2093j -0.0889-0.4329j  0.4846-0.0056j] |s|=3.67757e-07 |z|-1=-0.00904596
> tau=0.006 obj=6.484670 z= [-0.5890-0.2310j -0.3284-0.2089j -0.0886-0.4326j  0.4849-0.0057j] |s|=2.89781e-05 |z|-1=-0.00913031
> tau=0.007 obj=6.484329 z= [-0.5890-0.2310j -0.3284-0.2089j -0.0886-0.4326j  0.4849-0.0057j] |s|=1.70073e-07 |z|-1=-0.00913031
> tau=0.009 obj=6.484393 z= [-0.5890-0.2310j -0.3284-0.2080j -0.0878-0.4322j  0.4855-0.0060j] |s|=0 |z|-1=-0.00923817
> tau=0.010 obj=6.484194 z= [-0.5890-0.2310j -0.3284-0.2079j -0.0877-0.4322j  0.4856-0.0060j] |s|=1.04878e-05 |z|-1=-0.00924683
> tau=0.012 obj=6.484207 z= [-0.5890-0.2310j -0.3284-0.2079j -0.0877-0.4321j  0.4856-0.0060j] |s|=0 |z|-1=-0.00924344
> tau=0.015 obj=6.484111 z= [-0.5890-0.2309j -0.3286-0.2080j -0.0879-0.4320j  0.4856-0.0058j] |s|=0 |z|-1=-0.00922791
> tau=0.018 obj=6.484247 z= [-0.5890-0.2309j -0.3286-0.2080j -0.0879-0.4319j  0.4856-0.0057j] |s|=1.12794e-05 |z|-1=-0.0092249
> tau=0.021 obj=6.484487 z= [-0.5890-0.2308j -0.3287-0.2080j -0.0880-0.4319j  0.4856-0.0057j] |s|=6.42907e-06 |z|-1=-0.0092247
> tau=0.026 obj=6.484420 z= [-0.5890-0.2310j -0.3281-0.2078j -0.0875-0.4323j  0.4855-0.0062j] |s|=0.000152127 |z|-1=-0.00929503
> tau=0.031 obj=6.483778 z= [-0.5890-0.2312j -0.3280-0.2081j -0.0876-0.4327j  0.4853-0.0065j] |s|=3.65549e-05 |z|-1=-0.00919265
> tau=0.037 obj=6.482876 z= [-0.5890-0.2312j -0.3279-0.2080j -0.0875-0.4328j  0.4852-0.0066j] |s|=5.2042e-06 |z|-1=-0.00921108
> tau=0.045 obj=6.482962 z= [-0.5889-0.2310j -0.3286-0.2076j -0.0874-0.4317j  0.4860-0.0060j] |s|=0.00010974 |z|-1=-0.00934559
> tau=0.053 obj=6.482916 z= [-0.5888-0.2309j -0.3286-0.2075j -0.0873-0.4316j  0.4861-0.0060j] |s|=7.38182e-06 |z|-1=-0.00938081
> tau=0.064 obj=6.482959 z= [-0.5889-0.2309j -0.3284-0.2076j -0.0874-0.4319j  0.4858-0.0061j] |s|=5.87587e-05 |z|-1=-0.00939661
> tau=0.077 obj=6.482951 z= [-0.5889-0.2309j -0.3282-0.2079j -0.0876-0.4323j  0.4855-0.0062j] |s|=1.46451e-05 |z|-1=-0.00940434
> tau=0.092 obj=6.482914 z= [-0.5888-0.2309j -0.3277-0.2083j -0.0878-0.4329j  0.4850-0.0063j] |s|=4.81013e-06 |z|-1=-0.00944995
> tau=0.111 obj=6.482979 z= [-0.5889-0.2309j -0.3274-0.2086j -0.0880-0.4333j  0.4846-0.0064j] |s|=3.00837e-06 |z|-1=-0.00945962
> tau=0.133 obj=6.482617 z= [-0.5891-0.2309j -0.3272-0.2090j -0.0883-0.4338j  0.4841-0.0065j] |s|=0 |z|-1=-0.00933376
> tau=0.160 obj=6.482861 z= [-0.5891-0.2310j -0.3270-0.2095j -0.0887-0.4342j  0.4836-0.0066j] |s|=2.71405e-05 |z|-1=-0.00927872
> tau=0.192 obj=6.482033 z= [-0.5892-0.2311j -0.3261-0.2099j -0.0887-0.4354j  0.4828-0.0072j] |s|=3.60559e-05 |z|-1=-0.00929001
> tau=0.230 obj=6.481742 z= [-0.5892-0.2312j -0.3259-0.2102j -0.0889-0.4357j  0.4825-0.0073j] |s|=0 |z|-1=-0.00923723
> tau=0.276 obj=6.481647 z= [-0.5892-0.2311j -0.3259-0.2102j -0.0889-0.4358j  0.4825-0.0073j] |s|=2.2788e-06 |z|-1=-0.00924083
> tau=0.331 obj=6.481635 z= [-0.5892-0.2312j -0.3259-0.2102j -0.0889-0.4358j  0.4825-0.0073j] |s|=1.12743e-06 |z|-1=-0.00920357
> tau=0.397 obj=6.481642 z= [-0.5892-0.2312j -0.3259-0.2102j -0.0889-0.4358j  0.4825-0.0073j] |s|=0 |z|-1=-0.00920248
> tau=0.477 obj=6.481642 z= [-0.5892-0.2312j -0.3259-0.2102j -0.0889-0.4357j  0.4826-0.0073j] |s|=1.40257e-06 |z|-1=-0.00921438
> tau=0.572 obj=6.481506 z= [-0.5891-0.2313j -0.3263-0.2097j -0.0885-0.4351j  0.4831-0.0072j] |s|=4.66288e-05 |z|-1=-0.00925382
> tau=0.687 obj=6.480816 z= [-0.5891-0.2313j -0.3262-0.2099j -0.0886-0.4352j  0.4830-0.0072j] |s|=0 |z|-1=-0.00923296
> tau=0.824 obj=6.480926 z= [-0.5891-0.2314j -0.3265-0.2097j -0.0885-0.4349j  0.4833-0.0072j] |s|=3.74148e-05 |z|-1=-0.00915818
> tau=0.989 obj=6.481170 z= [-0.5890-0.2315j -0.3260-0.2100j -0.0885-0.4356j  0.4829-0.0075j] |s|=9.18383e-05 |z|-1=-0.00915256
> tau=1.187 obj=6.481236 z= [-0.5890-0.2315j -0.3260-0.2100j -0.0885-0.4356j  0.4830-0.0075j] |s|=3.93103e-06 |z|-1=-0.0091588
> tau=1.424 obj=6.481306 z= [-0.5891-0.2315j -0.3262-0.2098j -0.0884-0.4354j  0.4831-0.0075j] |s|=0 |z|-1=-0.0090821
> tau=1.709 obj=6.481486 z= [-0.5891-0.2315j -0.3260-0.2097j -0.0883-0.4355j  0.4831-0.0077j] |s|=0 |z|-1=-0.0091042
> tau=2.051 obj=6.481406 z= [-0.5891-0.2315j -0.3260-0.2097j -0.0883-0.4355j  0.4831-0.0077j] |s|=3.47586e-07 |z|-1=-0.00910462
> tau=2.461 obj=6.481626 z= [-0.5894-0.2314j -0.3265-0.2095j -0.0884-0.4351j  0.4832-0.0075j] |s|=0 |z|-1=-0.00899609
> tau=2.953 obj=6.481142 z= [-0.5893-0.2313j -0.3268-0.2092j -0.0882-0.4345j  0.4836-0.0072j] |s|=1.01765e-05 |z|-1=-0.00908948
> tau=3.544 obj=6.480920 z= [-0.5893-0.2314j -0.3268-0.2093j -0.0883-0.4346j  0.4836-0.0072j] |s|=1.86336e-05 |z|-1=-0.00907979
> tau=4.253 obj=6.481027 z= [-0.5895-0.2315j -0.3264-0.2100j -0.0887-0.4355j  0.4828-0.0075j] |s|=4.26936e-05 |z|-1=-0.00888421
> tau=5.103 obj=6.480190 z= [-0.5898-0.2314j -0.3257-0.2105j -0.0892-0.4365j  0.4817-0.0078j] |s|=9.85441e-05 |z|-1=-0.00880747
> tau=6.124 obj=6.481620 z= [-0.5899-0.2314j -0.3256-0.2105j -0.0892-0.4365j  0.4817-0.0078j] |s|=7.26592e-07 |z|-1=-0.00881728
> tau=7.349 obj=6.480465 z= [-0.5897-0.2316j -0.3250-0.2110j -0.0893-0.4373j  0.4813-0.0081j] |s|=0.00010177 |z|-1=-0.00884728
> tau=8.819 obj=6.481311 z= [-0.5897-0.2315j -0.3250-0.2110j -0.0893-0.4373j  0.4812-0.0081j] |s|=5.94555e-06 |z|-1=-0.00884649
> tau=10.582 obj=6.481378 z= [-0.5897-0.2316j -0.3253-0.2108j -0.0891-0.4369j  0.4816-0.0080j] |s|=2.13746e-05 |z|-1=-0.00878282
> tau=12.699 obj=6.480168 z= [-0.5899-0.2306j -0.3260-0.2098j -0.0892-0.4355j  0.4820-0.0072j] |s|=9.42288e-05 |z|-1=-0.00933503
> tau=15.239 obj=6.479315 z= [-0.5899-0.2303j -0.3263-0.2086j -0.0884-0.4345j  0.4830-0.0072j] |s|=2.95116e-05 |z|-1=-0.00956056
> tau=18.286 obj=6.480671 z= [-0.5899-0.2305j -0.3265-0.2083j -0.0880-0.4344j  0.4834-0.0074j] |s|=1.30242e-06 |z|-1=-0.00938293
> tau=21.944 obj=6.481634 z= [-0.5899-0.2306j -0.3267-0.2079j -0.0877-0.4341j  0.4839-0.0074j] |s|=0 |z|-1=-0.00934278
> tau=26.332 obj=6.481521 z= [-0.5899-0.2304j -0.3263-0.2086j -0.0883-0.4347j  0.4831-0.0074j] |s|=0 |z|-1=-0.00940782
> tau=31.599 obj=6.480954 z= [-0.5896-0.2302j -0.3266-0.2079j -0.0877-0.4339j  0.4839-0.0072j] |s|=4.54126e-06 |z|-1=-0.0097182
> tau=37.918 obj=6.480738 z= [-0.5898-0.2303j -0.3264-0.2079j -0.0877-0.4342j  0.4837-0.0074j] |s|=8.86706e-07 |z|-1=-0.00962823
> exact answer            = [-0.5203-0.1194j -0.2438-0.2327j -0.0218-0.5988j  0.4858-0.0798j]

**Comment by xinyueshen** [comment]
Hi @keithbriggs, of course you can implement the method yourself, but dccp already handles the problem in this example.

As for the expression `z^H@z`, out of various considerations it is not DCP. For details you can look into the DCP documentations, but it is not within the scope here.

**Comment by keithbriggs** [comment]
Yes, I know it can handle this example, but it fails on more general examples of this type, so I am working on my own code so I can fine-tune it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
