### ISSUE TITLE
DC variable split error

### ISSUE THREAD

**Issue by Kreol64** [cvxgrp/dccp#65]
Hi, 

I am trying to split x into two positive variables. Within dcp such trick works just fine, but dccp complains for some reason. What`s the way to make it work ? y * z <= 0 does not work either.

This works fine: 

import dccp
import cvxpy as cp

x = cp.Variable(1)
z = cp.Variable(1, nonneg=True) 
y = cp.Variable(1, nonneg=True) 
t = cp.Variable(1, nonneg=True)
h = (y - z)/2
g = y + z
f = g - t
obj = cp.Minimize(f)
prob = cp.Problem(obj, [t == h])
prob.solve(solver='ECOS',verbose=True, method='dccp')

This fails: 

import dccp
import cvxpy as cp

x = cp.Variable(1)
**z = cp.pos(x)
y = cp.pos(-x)**
t = cp.Variable(1, nonneg=True)
h = (y - z)/2
g = y + z
f = g - t
obj = cp.Minimize(f)
prob = cp.Problem(obj, [t == h])
prob.solve(solver='ECOS',verbose=True, method='dccp')

Thanks 
Kreol

p.s cvxpy: 1.0.21, dccp:1.0.0

**Comment by xinyueshen** [comment]
Hi @Kreol64, `h=(cp.pos(-x) - cp.pos(x))/2` has unknown curvature,  so the constraint `t==h` won't be recognized by dccp. You could try changing that constraint into `cp.pos(-x) = 2*t + cp.pos(x)`.

**Comment by Kreol64** [comment]
This one throws UNBOUNDED error ...

**Comment by xinyueshen** [comment]
You could set the parameter `tau` manually by the following.
`prob.solve(method='dccp', tau=1.0)`

**Comment by Kreol64** [comment]
@xinyueshen Thanks, it worked on the toy example ! But still failing on a bigger problem, but I suspect issue is similar. What`s the best way to "tell" dccp that my function is convex ? For example [this function](https://www.wolframalpha.com/input/?i=max%28%7Cx%7C-+%7Cx%7C+**+0.8%2C0%29) is not recognized as convex.

**Comment by xinyueshen** [comment]
dccp can only tell that a function is convex (concave, or affine), if the cvxpy expression is convex (concave, or affine) according to the rules of disciplined convex programming (DCP). As for how to construct a DCP convex function, you could look into the [cvxpy documentation](https://www.cvxpy.org/).

**Comment by Kreol64** [comment]
@xinyueshen thank you so much, this is very helpful. I indeed was trying to follow these, but sometimes the curvature is not resolved even for simple expressions. For example this one returns "CONVEX" : 

(cp.abs(x)).curvature

But this one returns "UNKNOWN": 

(cp.abs(x)**0.8).curvature

These are elementary expressions, so I am not sure how to simplify them such that the package could understand it.

**Comment by xinyueshen** [comment]
In general the way to construct expressions is to use [atomic functions](https://www.cvxpy.org/tutorial/functions/index.html) and [composition rules](https://www.cvxpy.org/tutorial/dcp/index.html).

Btw, |x|^{0.8} is not convex or concave on R. 
It is concave on R_+, and by using the power atom which automatically imposes domain R_+, it is DCP concave.

**Comment by Kreol64** [comment]
@xinyueshen , yep I tried power but it returns "UNKNOWN" as well: 

cp.power(cp.abs(x), 0.8).curvature 

I even tried to explicitly set: 

x = cp.Variable(1, nonneg=True)
cp.power(cp.abs(x), 0.8).curvature

**Comment by xinyueshen** [comment]
`cp.power(x, 0.8)` is DCP concave.
`cp.power(cp.abs(x), 0.8)` is not only DCP unknown, but also not convex or concave mathematically.

**Comment by Kreol64** [comment]
@xinyueshen sorry but I was talking about the case when x>=0. 
Should not the below return "CONCAVE" ?

x = cp.Variable(1, **nonneg=True**)
cp.power(cp.abs(x), 0.8).curvature

**Comment by xinyueshen** [comment]
No, because `cp.power(cp.abs(x), 0.8).curvature` returns the curvature on the domain of `cp.abs`, which is R, not R_+.
The curvature of an expression is local, i.e., it does not take the nonnegative flag in the definition of `x` into consideration.

**Comment by Kreol64** [comment]
@xinyueshen, thank you so much for clarification, this is really helpful to understand how the internal works. What would be the trick then to tell the package that the below is concave ? 

x = cp.Variable()
y = cp.pos(x)
cp.power(y, 0.6).curvature

**Comment by xinyueshen** [comment]
The following simply works.
```
x = cp.Variable(1)
cp.power(x, 0.6).curvature
```

**Comment by Kreol64** [comment]
I was still hoping to work with the |x| and wanted to split it into 2 positive variables first. Is there any chance curvature could be calculated for cp.pos(x) rather than x ? :)

**Comment by xinyueshen** [comment]
The composition of `cp.pos` and `cp.power` won't work.

You probably could get it work with a change of variables, such as `cp.power(y, 0.8)` and `cp.pos(x) <= y` or `cp.pos(x) == y`. But it depends on what the optimization problem is.

**Comment by Kreol64** [comment]
I see, thank you so much @xinyueshen for your help !
