### ISSUE TITLE
Significant memory performance differences in CVXPY and DCCP 

### ISSUE THREAD

**Issue by QCmonk** [cvxgrp/dccp#68]
Hello,

I was testing the limits of DCCP as compared to standard CVXPY and have ran into a significant memory scaling difference between the two. While I fully expect the time complexity to be incomparable it seems a little surprising that the memory requirements are so different when using the same solver with DCCP that was previously minimised efficiently. Consider the following optimisation problems over the bounded positive semidefinite cone
```
import cvxpy
import dccp
import numpy as np

# problem dimension
N = 200

rho = cp.Variable((N,N), complex=True)
cons =  [rho>>0, cp.trace(rho)==1.0, rho==rho.H]

prob = cp.Problem(cp.Minimize(cp.norm(rho - np.eye(N)/N)), cons)

prob.solve(verbose=True, solver=cp.SCS)
```
compared with 
```
import cvxpy
import dccp
import numpy as np

# problem dimension
N = 200

rho = cp.Variable((N,N), complex=True)
cons =  [rho>>0, cp.trace(rho)==1.0, rho==rho.H]

prob = cp.Problem(cp.Minimize(cp.norm(rho - np.eye(N)/N)), cons)

prob.solve(verbose=True, solver=cp.SCS, method="dccp")
```

Of course these are huge (though very simple) problems but the SCS solver and default method handles it exceptionally well with less than half a gigabyte of RAM required in the former case, whereas the DCCP method attempts to allocate a matrix requiring almost 36 gigabytes and on my system throws a memory error. Are there any changes that I can make that will improve the memory scaling while perhaps sacrificing performance? It seems strange to me that the memory requirements of DCCP would be so much greater. 

Perhaps I am missing something fundamental in how DCCP operates but it seems to me that the same solver should have the same memory requirements regardless of the method and perhaps only time complexity, precision and global convergence is changed. Is this not the case? I could understand some additional memory overhead required (perhaps a constant multiplicative) for the the heuristic but nothing quite so extreme. Any help would be greatly appreciated.

**Comment by xinyueshen** [comment]
Hi @QCmonk, currently DCCP is expected to take much more memory than CVXPY, because it is an iterative algorithm which solves a CVXPY problem in each iteration. But we'll have another implementation of DCCP using the concept of parameters in CVXPY, and it should be able to reduce the memory cost without any performance sacrificed. I'll let you know when it is ready.

**Comment by QCmonk** [comment]
Hello @xinyueshen, that would be outstanding and help me with a problem I have been working on for quite some time. Do you have an approximate time frame in mind?

**Comment by QCmonk** [comment]
Hi @xinyueshen, I have performed some further tests and I think the memory usage difference is more fundamental. Consider the following large feasibility program 

```
import dccp 
import cvxpy as cp

# problem dimension
N = 200 

rho = cp.Variable((N,N), hermitian=True)
cons = [cp.trace(rho)==1.0,rho>>0]

prob = cp.Problem(cp.Minimize(0), cons)

prob.solve(verbose=True, solver=cp.SCS)
```

and the same with DCCP and max_iterations set to one:

```
import dccp 
import cvxpy as cp

# problem dimension
N = 200 

rho = cp.Variable((N,N), hermitian=True)
cons = [cp.trace(rho)==1.0,rho>>0]

prob = cp.Problem(cp.Minimize(0), cons)

prob.solve(verbose=True, solver=cp.SCS, method="dccp", max_iter=1)
```

The former terminates successfully in a few seconds while the latter attempts to allocate a thirty gigabyte vector. This behaviour seems very surprising to me as in this case I would expect the two to have more or less the same scaling with these parameters.

**Comment by xinyueshen** [comment]
Hi @QCmonk, thanks for finding out this problem. Right, there's something not quite right with the automatic initialization, and we're looking into it. Right now you could try initializing the variable(s) by setting `rho = np.eye(N)` before calling the `.solve` function, and that should perform correctly.

**Comment by QCmonk** [comment]
Hi @xinyueshen, thank you for looking into that. Your suggestion does not appear to work however - placing ```rho=np.eye(N)``` at any point in the program before the solve command yields the same results.

**Comment by xinyueshen** [comment]
Hi @QCmonk, the code has just been updated, and you could try and see if it works now.

**Comment by QCmonk** [comment]
Hi @xinyueshen, yes this seems to make a big difference thank you.
