### ISSUE TITLE
pip install dccp==1.0.4 failed, while 1.0.3 works well

### ISSUE THREAD

**Issue by Rex-sys-hk** [cvxgrp/dccp#78]
The error info is
```
pip install dccp
Collecting dccp
  Using cached dccp-1.0.4.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in dccp setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I'm using python 3.9

**Comment by xinyueshen** [comment]
Thanks @Rex-sys-hk for using DCCP and reporting the error. Currently to install the most updated DCCP, please download the repository and run `python setup.py install` inside.

**Comment by QCmonk** [comment]
Hi @xinyueshen, downloading the repository, extracting it and running setup.py returns the same ''error in dccp setup command: use_2to3 is invalid' error. This is on a fresh environment with only cvxpy and its dependents installed.

Installing using `pip install dccp=1.0.3` works as usual however.

**Comment by xinyueshen** [comment]
Hi @QCmonk, according to https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2, it might be a `setuptools` version problem. Could you please temporarily try `setuptools<58`?

**Comment by alevalcar** [comment]
After having setuptools<58, also make sure to have wheel installed. I had this same problem, and nothing was solving it for installation. The command would be 
pip install "setuptools<58.0.0" wheel
and then the regular install for dccp. Make sure you do this after installing cvxpy 1.1
