### ISSUE TITLE
DOC: typo and grammar

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/dccp#79]
`> the obejctive and the constraints has any known curvature `

probably should be 

`the objective and the constraints have a known curvature `

**Comment by xinyueshen** [comment]
> `> the obejctive and the constraints has any known curvature `
> 
> probably should be
> 
> `the objective and the constraints have a known curvature `

`every function in the obejctive and the constraints has any known curvature`

**Comment by keithbriggs** [comment]
Thanks, but the typo is still not fixed, and the grammar is unclear. What about: 

every function in the objective and in the constraints has one of the known curvature types

?

**Comment by xinyueshen** [comment]
Thanks for your concern. It is not a typo or grammar error.

**Comment by keithbriggs** [comment]
"obejctive" is definitely a typo.

**Comment by xinyueshen** [comment]
> "obejctive" is definitely a typo.

It's been corrected. Thank you.
