### ISSUE TITLE
Fixed addition of slack variables to new objective in problem.py

### ISSUE THREAD

**Issue by dave31415** [cvxgrp/dccp#8]
I fixed a bug that was causing the Minimize not to resolve to a scalar. Had to add the sum_entries function for it to work on a non-scalar variable. Around line 355 in dccp/problem.py

    # objective
        if self.objective.NAME == 'minimize':
            for var in var_slack:
                #BUG FIX added sum_entries
                #cost_new += np.ones((var._cols,var._rows)*var*tau)
                cost_new += tau*sum_entries(var)
            obj_new = Minimize(cost_new)
        else:
            for var in var_slack:
                #BUG FIX here too
                cost_new -= taur*sum_entries(var)
            obj_new = Maximize(cost_new)

**Comment by stephenpboyd** [comment]
david, thank you so much!

as you can see, dccp is still quite preliminary.

stephen

**Comment by SteveDiamond** [comment]
Thanks for finding this David! I've fixed the bug and pushed the new release to pypi.

**Comment by dave31415** [comment]
This same bug needs fixing around line 355 as well. Opened another issue.

David Johnston
Principal Data Scientist, ThoughtWorks
dajohnst@thoughtworks.com
c: 773 600-9417
LinkedIn <https://www.linkedin.com/in/david-johnston-a0b84436>
