### ISSUE TITLE
linearize in linearize.py doesn't work with variables of size (1,N)

### ISSUE THREAD

**Issue by dave31415** [cvxgrp/dccp#9]
I patched this for now but it probably needs a better solution. 

if var.is_matrix() or True:
                # forcing this route for now
                flattened = np.transpose(grad_map[var])*vec(var - var.value)
                tangent = tangent + reshape(flattened, *expr.size)
            else:
                # THIS appears to be broken for variables like (1,N)
                # using the matrix version above works
                # TODO: fix this correctly
                tangent = tangent + np.transpose(grad_map[var])*(var - var.value)

**Comment by SteveDiamond** [comment]
This is fixed now and pushed to pypi. Thanks again for helping us work out these bugs!
